# Generated by Django 4.2.30 on 2026-04-11 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='fingerprint',
            new_name='songs_finge_hash_va_e4b7f4_idx',
            old_name='songs_finge_hash_va_idx',
        ),
    ]
