# Generated by Django 4.2.30 on 2026-04-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_rename_songs_finge_hash_va_idx_songs_finge_hash_va_e4b7f4_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
